const mockColorBoxConfig = [
  {
    id: 1,
    color: "red",
    width: 100,
    height: 100,
    borderColor: "black",
    borderWidth: 2,
  },
  {
    id: 2,
    color: "blue",
    width: 150,
    height: 150,
    borderColor: "white",
    borderWidth: 3,
  },
  {
    id: 3,
    color: "green",
    width: 200,
    height: 200,
    borderColor: "yellow",
    borderWidth: 1,
  },
  {
    id: 4,
    color: "purple",
    width: 120,
    height: 120,
    borderColor: "gray",
    borderWidth: 4,
  },
  {
    id: 5,
    color: "orange",
    width: 80,
    height: 80,
    borderColor: "blue",
    borderWidth: 2,
  },
  {
    id: 6,
    color: "pink",
    width: 90,
    height: 90,
    borderColor: "red",
    borderWidth: 1,
  },
  {
    id: 7,
    color: "yellow",
    width: 110,
    height: 110,
    borderColor: "black",
    borderWidth: 5,
  },
  {
    id: 8,
    color: "cyan",
    width: 140,
    height: 140,
    borderColor: "green",
    borderWidth: 2,
  },
  {
    id: 9,
    color: "magenta",
    width: 160,
    height: 160,
    borderColor: "purple",
    borderWidth: 3,
  },
  {
    id: 10,
    color: "brown",
    width: 130,
    height: 130,
    borderColor: "pink",
    borderWidth: 1,
  },
  {
    id: 1,
    color: "red",
    width: 100,
    height: 100,
    borderColor: "black",
    borderWidth: 2,
  },
  {
    id: 2,
    color: "blue",
    width: 150,
    height: 150,
    borderColor: "white",
    borderWidth: 3,
  },
  {
    id: 3,
    color: "green",
    width: 200,
    height: 200,
    borderColor: "yellow",
    borderWidth: 1,
  },
  {
    id: 4,
    color: "purple",
    width: 120,
    height: 120,
    borderColor: "gray",
    borderWidth: 4,
  },
  {
    id: 5,
    color: "orange",
    width: 80,
    height: 80,
    borderColor: "blue",
    borderWidth: 2,
  },
  {
    id: 6,
    color: "pink",
    width: 90,
    height: 90,
    borderColor: "red",
    borderWidth: 1,
  },
  {
    id: 7,
    color: "yellow",
    width: 110,
    height: 110,
    borderColor: "black",
    borderWidth: 5,
  },
  {
    id: 8,
    color: "cyan",
    width: 140,
    height: 140,
    borderColor: "green",
    borderWidth: 2,
  },
  {
    id: 9,
    color: "magenta",
    width: 160,
    height: 160,
    borderColor: "purple",
    borderWidth: 3,
  },
  {
    id: 10,
    color: "brown",
    width: 130,
    height: 130,
    borderColor: "pink",
    borderWidth: 1,
  },
  {
    id: 1,
    color: "red",
    width: 100,
    height: 100,
    borderColor: "black",
    borderWidth: 2,
  },
  {
    id: 2,
    color: "blue",
    width: 150,
    height: 150,
    borderColor: "white",
    borderWidth: 3,
  },
  {
    id: 3,
    color: "green",
    width: 200,
    height: 200,
    borderColor: "yellow",
    borderWidth: 1,
  },
  {
    id: 4,
    color: "purple",
    width: 120,
    height: 120,
    borderColor: "gray",
    borderWidth: 4,
  },
  {
    id: 5,
    color: "orange",
    width: 80,
    height: 80,
    borderColor: "blue",
    borderWidth: 2,
  },
  {
    id: 6,
    color: "pink",
    width: 90,
    height: 90,
    borderColor: "red",
    borderWidth: 1,
  },
  {
    id: 7,
    color: "yellow",
    width: 110,
    height: 110,
    borderColor: "black",
    borderWidth: 5,
  },
  {
    id: 8,
    color: "cyan",
    width: 140,
    height: 140,
    borderColor: "green",
    borderWidth: 2,
  },
  {
    id: 9,
    color: "magenta",
    width: 160,
    height: 160,
    borderColor: "purple",
    borderWidth: 3,
  },
  {
    id: 10,
    color: "brown",
    width: 130,
    height: 130,
    borderColor: "pink",
    borderWidth: 1,
  },
  {
    id: 1,
    color: "red",
    width: 100,
    height: 100,
    borderColor: "black",
    borderWidth: 2,
  },
  {
    id: 2,
    color: "blue",
    width: 150,
    height: 150,
    borderColor: "white",
    borderWidth: 3,
  },
  {
    id: 3,
    color: "green",
    width: 200,
    height: 200,
    borderColor: "yellow",
    borderWidth: 1,
  },
  {
    id: 4,
    color: "purple",
    width: 120,
    height: 120,
    borderColor: "gray",
    borderWidth: 4,
  },
  {
    id: 5,
    color: "orange",
    width: 80,
    height: 80,
    borderColor: "blue",
    borderWidth: 2,
  },
  {
    id: 6,
    color: "pink",
    width: 90,
    height: 90,
    borderColor: "red",
    borderWidth: 1,
  },
  {
    id: 7,
    color: "yellow",
    width: 110,
    height: 110,
    borderColor: "black",
    borderWidth: 5,
  },
  {
    id: 8,
    color: "cyan",
    width: 140,
    height: 140,
    borderColor: "green",
    borderWidth: 2,
  },
  {
    id: 9,
    color: "magenta",
    width: 160,
    height: 160,
    borderColor: "purple",
    borderWidth: 3,
  },
  {
    id: 10,
    color: "brown",
    width: 130,
    height: 130,
    borderColor: "pink",
    borderWidth: 1,
  },
];
const renderColorBoxes = (config) => {
  const container = document.getElementById("color-boxes-container");
  container.innerHTML = "";

  config.forEach((box) => {
    const div = document.createElement("div");
    div.style.backgroundColor = box.color;
    div.style.width = `${box.width}px`;
    div.style.height = `${box.height}px`;
    div.style.border = `${box.borderWidth}px solid ${box.borderColor}`;
    div.style.margin = "5px";
    div.style.display = "inline-block";
    container.appendChild(div);
  });
  container.addEventListener("click", (event) => {
    const clicked = event.target;
    if (clicked?.style?.backgroundColor) alert(`${clicked.style.backgroundColor} box is clicked`);
  });
};

// Example usage
document.addEventListener("DOMContentLoaded", () => {
  renderColorBoxes(mockColorBoxConfig);
});
